name: Frontend CD to Google Cloud Run
on:
  push:
    branches:
      - main
  workflow_dispatch: {}
permissions:
  contents: read
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production
      url: ${{ steps.deploy-to-cloud-run.outputs.url }}

    env:
      GCP_PROJECT_ID: 'oidc-github-01'
      GCP_REGION: "us-central1"
      SERVICE_NAME: "blog-frontend-service"
      IMAGE_NAME: "blog-frontend"
      GCP_WIF_PROVIDER: "projects/1010347128743/locations/global/workloadIdentityPools/github-pool/providers/github-provider"
      GCP_WIF_SA: "cloudrun-deployer@oidc-github-01.iam.gserviceaccount.com"

    steps:
      - uses: actions/checkout@v4
      # Define and log in to Docker Hub using credentials stored in GitHub Secrets.
      - name: Log in to Docker Hub
        uses: docker/login-action@v4
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Authenticate to GCP using Workload Identity Federation
    